---
name: TESTE 2024 04 28 Build Matrix

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./src

jobs:
  ListProjects:
    runs-on: ubuntu-latest
    outputs:
      PROJECTS: ${{steps.set-projects.outputs.PROJEcTS}}
      FIXO: ${{steps.set-projects.outputs.FIXO}}
    steps:
      - uses: actions/checkout@v4
      - id: set-projects
        run: |
          LIST="$(find . -mindepth 1 -maxdepth 1 -type d \
          | sort \
          | xargs -n1 basename \
          | jq -R -s -c 'split("\n")[:-1]')"
          VALOR="valor fixo"
            echo "FIXO=${VALOR}" >> "${GITHUB_OUTPUT}"
            echo "PROJECTS=${LIST}" >> "${GITHUB_OUTPUT}"
      - run: |
          echo "${{steps.set-projects.outputs.FIXO}}"
          echo "${{steps.set-projects.outputs.PROJECTS}}"

  teste-A:
    runs-on: ubuntu-latest
    env:
      PROJECTS: ${{needs.ListProjects.outputs.PROJECTS}}
      FIXO: ${{needs.ListProjects.outputs.FIXO}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ env.FIXO }}"
          echo "${{ env.PROJECTS }}"

  teste-B:
    runs-on: ubuntu-latest
    env:
      PROJECTS: ${{needs.ListProjects.outputs.PROJECTS}}
    steps:
      - uses: actions/checkout@v4
      - run:
          echo "${env.PROJECTS}" | jq -r '.[]'

  build-with-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{fromJson(needs.ListProjects.outputs.PROJECTS)}}
    steps:
      - run: echo "${{ matrix.project }}"
