---
name: TESTE 2024 04 28 Build Matrix

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./src

jobs:
  listProjects:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.generateList.outputs.projects }}
    steps:
      - uses: actions/checkout@v4
      - id: generateList
        run: |
          valueB="$(find . -mindepth 1 -maxdepth 1 -type d \
          | sort \
          | xargs -n1 basename \
          | jq -R -s -c 'split("\n")[:-1]')"
          echo "projects=${valueB}" >> "$GITHUB_OUTPUT"

  build-with-matrix:
    runs-on: ubuntu-latest
    needs: listProjects
    strategy:
      matrix:
        project: ${{fromJson(needs.listProjects.outputs.projects)}}
    steps:
      - uses: actions/checkout@v4
      - run: cat "${{ matrix.project }}/settings.conf"
